# Generated by Django 4.0.2 on 2022-02-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_cat',
            field=models.CharField(max_length=64, verbose_name='Nome'),
        ),
    ]
